document.addEventListener('DOMContentLoaded',()=>{
  const start=document.getElementById('start'),stop=document.getElementById('stop'),add=document.getElementById('addCandidate'),save=document.getElementById('saveContent');
  let draft=JSON.parse(JSON.stringify(window.loadContent()));
  const editor=document.getElementById('candidateEditor');
  const draw=()=>{editor.innerHTML=draft.candidates.map((c,i)=>`<div class="editor-card"><div class="editor-line"><b>เบอร์ ${c.no}</b><button type="button" class="remove-candidate" data-index="${i}">ลบ</button></div><input data-i="${i}" data-k="no" value="${c.no}" placeholder="หมายเลข"><input data-i="${i}" data-k="name" value="${c.name}" placeholder="ชื่อผู้สมัคร"><input data-i="${i}" data-k="team" value="${c.team}" placeholder="ทีม / พรรค"><input data-i="${i}" data-k="image" value="${c.image||''}" placeholder="ลิงก์รูปภาพ"></div>`).join('');editor.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>{draft.candidates[x.dataset.i][x.dataset.k]=x.value}));editor.querySelectorAll('.remove-candidate').forEach(x=>x.addEventListener('click',()=>{if(draft.candidates.length>1){draft.candidates.splice(+x.dataset.index,1);draw()}}))};
  document.getElementById('editTitle').value=draft.site.title;document.getElementById('editSubtitle').value=draft.site.subtitle;document.getElementById('editLogo').value=draft.site.logo||'';draw();
  start.addEventListener('click',()=>window.demo.start());stop.addEventListener('click',()=>window.demo.stop());
  add.addEventListener('click',()=>{const used=draft.candidates.map(c=>+c.no);let no=1;while(used.includes(no))no++;draft.candidates.push({no:String(no),name:'ผู้สมัครใหม่',team:'ทีมใหม่',image:''});draw()});
  save.addEventListener('click',()=>{draft.site={title:document.getElementById('editTitle').value.trim()||'การเลือกตั้ง',subtitle:document.getElementById('editSubtitle').value.trim(),logo:document.getElementById('editLogo').value.trim()};window.saveContent(draft);alert('บันทึกข้อมูลเรียบร้อยแล้ว')});
});
