document.addEventListener('DOMContentLoaded',()=>{
  const gate=document.getElementById('loginGate'),app=document.getElementById('adminApp'),form=document.getElementById('loginForm');
  const unlock=()=>{gate.classList.add('hidden');app.classList.remove('hidden');sessionStorage.setItem('election-admin-auth','1')};
  if(sessionStorage.getItem('election-admin-auth')==='1') unlock();
  form.addEventListener('submit',e=>{e.preventDefault();if(document.getElementById('loginUser').value==='admin'&&document.getElementById('loginPass').value==='0648587699')unlock();else document.getElementById('loginError').textContent='ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'});
  document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem('election-admin-auth');location.reload()});
  const d=loadContent();let draft=JSON.parse(JSON.stringify(d));const editor=document.getElementById('candidateEditor');
  const draw=()=>{editor.innerHTML=draft.candidates.map((c,i)=>`<div class="editor-card"><div class="editor-line"><b>เบอร์ ${c.no}</b><button type="button" class="remove-candidate" data-index="${i}">ลบ</button></div><input data-i="${i}" data-k="no" value="${c.no}" placeholder="หมายเลข"><input data-i="${i}" data-k="name" value="${c.name}" placeholder="ชื่อผู้สมัคร"><input data-i="${i}" data-k="team" value="${c.team}" placeholder="ทีม / พรรค"><input data-i="${i}" data-k="image" value="${c.image||''}" placeholder="ลิงก์รูปภาพ"></div>`).join('');editor.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>draft.candidates[x.dataset.i][x.dataset.k]=x.value));editor.querySelectorAll('.remove-candidate').forEach(x=>x.addEventListener('click',()=>{if(draft.candidates.length>1){draft.candidates.splice(+x.dataset.index,1);draw()}}))};
  document.getElementById('editTitle').value=draft.site.title;document.getElementById('editSubtitle').value=draft.site.subtitle;document.getElementById('editLogo').value=draft.site.logo||'';draw();
  document.getElementById('start').addEventListener('click',()=>window.demo.start());document.getElementById('stop').addEventListener('click',()=>window.demo.stop());
  document.getElementById('addCandidate').addEventListener('click',()=>{const used=draft.candidates.map(c=>+c.no);let no=1;while(used.includes(no))no++;draft.candidates.push({no:String(no),name:'ผู้สมัครใหม่',team:'ทีมใหม่',image:''});draw()});
  document.getElementById('saveContent').addEventListener('click',()=>{draft.site={title:document.getElementById('editTitle').value.trim()||'การเลือกตั้ง',subtitle:document.getElementById('editSubtitle').value.trim(),logo:document.getElementById('editLogo').value.trim()};window.saveContent(draft);alert('บันทึกข้อมูลเรียบร้อยแล้ว')});
  function drawChart(){const rows=[...document.querySelectorAll('.admin-row')],chart=document.getElementById('voteChart');if(!chart)return;const vals=rows.map(r=>({name:r.querySelector('span').textContent.replace(/^\d+\. /,''),vote:+r.querySelector('b').textContent.replace(/,/g,'')})),max=Math.max(1,...vals.map(x=>x.vote));chart.innerHTML=vals.map(x=>`<div class="chart-item"><div class="chart-label"><span>${x.name}</span><b>${x.vote}</b></div><div class="chart-track"><i style="width:${x.vote/max*100}%"></i></div></div>`).join('')};setInterval(drawChart,700);setTimeout(drawChart,100);
});
